### ISSUE TITLE
Manage table showing duplicate users

### ISSUE THREAD

**Issue by shampine** [GunnJerkens/plumage#15]
![screen shot 2015-01-13 at 5 13 11 pm](https://cloud.githubusercontent.com/assets/1027737/5732497/8db55206-9b47-11e4-835d-fdd18834bdb9.png)

**Comment by shampine** [comment]
This happens due to the table join happening in ViewController.php, when a user accesses from a different IP a separate throttle is created. If they have accessed from 2 IPs they will become 2 users in the join. Join needs to be modified to be aware of this possibility.

**Comment by shampine** [comment]
To duplicate, access the site as an admin via two different IPs. This will trigger to additions to the throttles table.

**Comment by joesgit** [comment]
Seems to be a known issue.

https://github.com/cartalyst/sentry/issues/159

**Comment by shampine** [comment]
I don't expect a large users list, we could filter the list before displaying it to drop any duplicates.
