### ISSUE TITLE
If no "Type" is set in a project, you cannot delete project.

### ISSUE THREAD

**Issue by joesgit** [GunnJerkens/plumage#46]
-Create new project
-Try deleting project without adding any "types"

**Comment by steveshadows** [comment]
Will this solve our issue for the plan/site use cases getting deleted? thanks Joe

**Comment by shampine** [comment]
@steveshadows no, issue #43 covers that.

Error is `Error delete all type sets.` -- this most likely is the result of need a method call of object()->forceDelete. Not sure though, might look into this a bit later today.
