### ISSUE TITLE
Deleting a type does not always delete matching db column

### ISSUE THREAD

**Issue by shampine** [GunnJerkens/plumage#59]
Columns are being left behind which causes issues when trying to then create a column of the same name.

**Comment by guitarbeard** [comment]
I couldn't replicate. Is there a specific case this fails in?

**Comment by shampine** [comment]
Potentially is already resolved, it's all older bug.

**Comment by guitarbeard** [comment]
This did happen to me, although it might have been related to the the php setting: max_input_vars which I had to change to get editing the test data to work.

**Comment by guitarbeard** [comment]
still couldn't replicate, closing.
