### ISSUE TITLE
ErrorException undefined type in template

### ISSUE THREAD

**Issue by shampine** [GunnJerkens/plumage#61]
```
Next exception 'ErrorException' with message 'Undefined property: stdClass::$sqft (View: /var/www/plumage.gjtouchscreen.com/app/views/layouts/type.blade.php)' in /var/www/plumage.gjtouchscreen.com/app/storage/views/d80d15c95a7a45789771e19adab5bff1:40
```

This is a two part kind of issue, data has been dropped from the types table but is left behind in the types json structure. We need to make sure that when data is dropped the structure matches exactly. We also need to check isset() when displaying data so that if the json data says a column exists when it doesn't the page still loads without that data.

**Comment by guitarbeard** [comment]
Not exactly sure how to recreate this. I deleted some data from the types table and also removed some fields but no errors.

**Comment by shampine** [comment]
I think it is more of a protective measure, iirc the columns are laid out by the json store of the columns. So we are just assuming that column exists. I'm playing around with this now, it's an old one as well.
