### ISSUE TITLE
Move Status Column to First Adjustable Column

### ISSUE THREAD

**Issue by steveshadows** [GunnJerkens/plumage#66]
Right now the status column is all the way to the right....so the user has to scroll all the way laterally to the right and cannot see the lot number to easily match it up to the status they're adjusting. 
![scroll to right to view status](https://cloud.githubusercontent.com/assets/3946404/10296692/e4bad3ec-6b7f-11e5-99f1-66b458be72fc.png)

**Comment by shampine** [comment]
Just drag and drop the column to an earlier position. It is up to the type creator to choose their order of columns.

Nothing to fix, closing.
